trigger:
  batch: true
  branches:
    include:
    - master
    - develop
    - release
  paths:
    include:
    - '*'
    exclude:
    - .azuredevops/*
    - docs/*
    - catalog-info.yaml
    - mkdocs.yml
    - scripts.py
    - catalog/*

resources:
  repositories:
    - repository: CorePipelines
      name: DevOps/fapp.core.pipelines
      type: git       
      ref: refs/tags/latest

extends:
  template: /provisioners/entrypoint.yml@CorePipelines
  parameters:
    config: 
      pipelineType: app
      technology: nextjs
      modelName: gitflow