# NUNCA DEFINA VALORES ABERTOS/PUBLICOS/VISÍVEL AQUI!
# Sempre utilize os marcadores de substituição $(NOME-DA-SECRET-LIBRARY-AZURE-DEVOPS).
# Valores aberto devem ser definidos no arquivo environments_variables.yaml conforme o ambiente na pasta .azuredevops/helm 
secrets: []
# - name: NOME_DA_MINHA_VARIAVEL
#   value: "$(REFERENCIA-A-MINHA-VARIAVEL-NO-AZURE-DEVOPS-DEV)"

secretFiles: []
